import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), role: text('role').notNull().default('user'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const groups = pgTable('groups', { id: text('id').primaryKey(), name: text('name').notNull().unique(), description: text('description').notNull().default(''), isDefault: boolean('isDefault').notNull().default(false), rateLimit: integer('rateLimit').notNull().default(60), dailyLimit: integer('dailyLimit').notNull().default(-1), weeklyLimit: integer('weeklyLimit').notNull().default(-1), monthlyLimit: integer('monthlyLimit').notNull().default(-1), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const groupMemberships = pgTable('group_memberships', { id: text('id').primaryKey(), userId: text('userId').notNull(), groupId: text('groupId').notNull(), startsAt: timestamp('startsAt').notNull().defaultNow(), expiresAt: timestamp('expiresAt'), source: text('source').notNull().default('default'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const redeemCodes = pgTable('redeem_codes', { id: text('id').primaryKey(), code: text('code').notNull().unique(), kind: text('kind').notNull().default('group'), groupId: text('groupId'), credits: integer('credits'), durationDays: integer('durationDays').notNull().default(30), durationValue: integer('durationValue').notNull().default(30), durationUnit: text('durationUnit').notNull().default('day'), expiresAt: timestamp('expiresAt'), redeemedAt: timestamp('redeemedAt'), redeemedBy: text('redeemedBy'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const creditGrants = pgTable('credit_grants', { id: text('id').primaryKey(), userId: text('userId').notNull(), credits: integer('credits').notNull(), remainingCredits: integer('remainingCredits').notNull(), expiresAt: timestamp('expiresAt'), source: text('source').notNull().default('redeem'), redeemCodeId: text('redeemCodeId'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const apiUsage = pgTable('api_usage', { id: text('id').primaryKey(), userId: text('userId').notNull(), usageDate: text('usageDate').notNull(), requestCount: integer('requestCount').notNull().default(0), windowStartedAt: timestamp('windowStartedAt').notNull().defaultNow(), windowCount: integer('windowCount').notNull().default(0) })
export const appSettings = pgTable('app_settings', { key: text('key').primaryKey(), value: text('value').notNull(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const afadianBenefitRules = pgTable('afadian_benefit_rules', { id: text('id').primaryKey(), benefitKey: text('benefitKey').notNull().unique(), name: text('name').notNull().default(''), kind: text('kind').notNull(), groupId: text('groupId'), credits: integer('credits'), durationValue: integer('durationValue').notNull().default(1), durationUnit: text('durationUnit').notNull().default('month'), codesPerItem: integer('codesPerItem').notNull().default(1), enabled: boolean('enabled').notNull().default(true), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const afadianOrders = pgTable('afadian_orders', { id: text('id').primaryKey(), outTradeNo: text('outTradeNo').notNull().unique(), userId: text('userId'), benefitKey: text('benefitKey'), generatedCodes: text('generatedCodes').notNull().default('[]'), payload: text('payload').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const allTables = { user, session, account, verification, groups, groupMemberships, redeemCodes, creditGrants, apiUsage, appSettings, afadianBenefitRules, afadianOrders }
