import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const groups = pgTable('groups', { id: text('id').primaryKey(), name: text('name').notNull().unique(), description: text('description').notNull().default(''), isDefault: boolean('isDefault').notNull().default(false), rateLimit: integer('rateLimit').notNull().default(60), dailyLimit: integer('dailyLimit'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const groupMemberships = pgTable('group_memberships', { id: text('id').primaryKey(), userId: text('userId').notNull(), groupId: text('groupId').notNull(), startsAt: timestamp('startsAt').notNull().defaultNow(), expiresAt: timestamp('expiresAt'), source: text('source').notNull().default('default'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const redeemCodes = pgTable('redeem_codes', { id: text('id').primaryKey(), code: text('code').notNull().unique(), groupId: text('groupId').notNull(), durationDays: integer('durationDays').notNull(), expiresAt: timestamp('expiresAt'), redeemedAt: timestamp('redeemedAt'), redeemedBy: text('redeemedBy'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const apiUsage = pgTable('api_usage', { id: text('id').primaryKey(), userId: text('userId').notNull(), usageDate: text('usageDate').notNull(), requestCount: integer('requestCount').notNull().default(0), windowStartedAt: timestamp('windowStartedAt').notNull().defaultNow(), windowCount: integer('windowCount').notNull().default(0) })
export const appSettings = pgTable('app_settings', { key: text('key').primaryKey(), value: text('value').notNull(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const afadianOrders = pgTable('afadian_orders', { id: text('id').primaryKey(), outTradeNo: text('outTradeNo').notNull().unique(), userId: text('userId'), payload: text('payload').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const allTables = { user, session, account, verification, groups, groupMemberships, redeemCodes, apiUsage, appSettings, afadianOrders }
