import { CheckCircle2, CircleDollarSign, PackageCheck } from 'lucide-react'
import { requireSession } from '@/lib/account'
import { getAccountOrders } from '@/lib/account/read-models'
import { EmptyState, PageIntro, Panel, Status, formatDate } from '@/components/account/ui'

export default async function OrdersPage() {
  const session = await requireSession()
  const rows = await getAccountOrders(session.user.id)
  return <><PageIntro eyebrow="ORDERS" title="我的订单" description="订单、支付、兑换码和订阅状态在这里形成闭环；只会展示与你当前账户关联的记录。"/><Panel>{rows.length ? <div className="divide-y divide-slate-100">{rows.map((order) => <article key={`${order.id}:${order.redeemCode || ''}`} className="py-5 first:pt-0 last:pb-0"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{order.skuName || order.offerTitle || 'AccessHub 商品'}</h3><Status tone={order.status === 'paid' || order.paymentStatus === 'paid' ? 'green' : 'amber'}>{statusLabel(order.status)}</Status></div><p className="mt-2 text-[11px] text-slate-400">订单 {order.id} · {formatDate(order.createdAt, true)}</p></div><p className="text-lg font-semibold">{order.amount ? `${order.currency === 'CNY' ? '¥' : `${order.currency} `}${order.amount}` : '—'}</p></div><div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 text-xs sm:grid-cols-3"><OrderState icon={<CircleDollarSign size={15}/>} label="支付" value={statusLabel(order.paymentStatus)}/><OrderState icon={<PackageCheck size={15}/>} label="履约" value={statusLabel(order.deliveryStatus)}/><OrderState icon={<CheckCircle2 size={15}/>} label="订阅" value={statusLabel(order.subscriptionStatus)}/></div>{order.redeemCode && <div className="mt-3 flex flex-col gap-2 rounded-xl border border-blue-100 bg-blue-50/60 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] text-blue-500">订单兑换码</p><code className="mt-1 block text-sm font-semibold tracking-wider text-blue-800">{order.redeemCode}</code></div><Status tone={order.redeemedAt ? 'green' : 'blue'}>{order.redeemedAt ? `已于 ${formatDate(order.redeemedAt)} 核销` : '等待核销'}</Status></div>}</article>)}</div> : <EmptyState>当前账户还没有关联订单。爱发电购买完成后，绑定同一身份即可在这里查看。</EmptyState>}</Panel></>
}
function OrderState({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-2"><span className="text-slate-400">{icon}</span><span className="text-slate-400">{label}</span><strong className="ml-auto font-medium text-slate-700">{value}</strong></div> }
function statusLabel(value: string | null) { if (!value) return '暂无'; return ({ paid: '已支付', pending: '处理中', completed: '已完成', delivered: '已送达', active: '生效中', pending_activation: '待激活', failed: '失败', canceled: '已取消', refunded: '已退款' } as Record<string, string>)[value] || value }
