import { CheckCircle2, CircleDollarSign, PackageCheck } from 'lucide-react'
import { requireSession } from '@/lib/account'
import { getAccountOrders } from '@/lib/account/read-models'
import { EmptyState, PageIntro, Panel, Status, formatDate } from '@/components/account/ui'
import { OrderCodeActions } from '@/components/account/order-code-actions'

export default async function OrdersPage() {
  const session = await requireSession()
  const rows = await getAccountOrders(session.user.id)
  return <><PageIntro eyebrow="我的订单" title="从支付到权益，一步不丢" description="已绑定爱发电后，尚未核销的订单也会出现在这里。订单中的兑换码只对当前账户展示。"/><Panel>{rows.length ? <div className="divide-y divide-slate-100">{rows.map((order) => <article key={`${order.id}:${order.redeemCode || ''}`} className="py-6 first:pt-0 last:pb-0"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{order.skuName || order.offerTitle || 'AccessHub 商品'}</h3><Status tone={order.status === 'paid' || order.paymentStatus === 'paid' ? 'green' : order.status === 'failed' ? 'rose' : 'amber'}>{statusLabel(order.status)}</Status><span className="text-[10px] text-slate-400">{order.providerId === 'psp-afdian' ? '爱发电' : '平台订单'}</span></div><p className="mt-2 break-all text-[11px] tabular-nums text-slate-400">订单 {order.id} · {formatDate(order.createdAt, true)}</p></div><div className="sm:text-right"><p className="text-xl font-semibold tabular-nums">{order.amount ? `${order.currency === 'CNY' ? '¥' : `${order.currency} `}${order.amount}` : '—'}</p>{order.termMonths > 1 && <p className="mt-1 text-[11px] text-slate-400">{order.termMonths} 个月权益周期</p>}</div></div><div className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-4 text-xs sm:grid-cols-3"><OrderState icon={<CircleDollarSign size={15}/>} label="支付" value={statusLabel(order.paymentStatus)}/><OrderState icon={<PackageCheck size={15}/>} label="发码" value={statusLabel(order.deliveryStatus)}/><OrderState icon={<CheckCircle2 size={15}/>} label="订阅" value={statusLabel(order.subscriptionStatus)}/></div>{order.redeemCode && <div className={`mt-3 rounded-xl border px-4 py-4 ${order.redeemedAt ? 'border-slate-100 bg-slate-50/70' : 'border-blue-100 bg-blue-50/60'}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="text-[11px] text-slate-400">订单兑换码</p><Status tone={order.redeemedAt ? 'green' : 'blue'}>{order.redeemedAt ? `已于 ${formatDate(order.redeemedAt)} 核销` : '等待核销'}</Status></div><code className="mt-2 block break-all text-sm font-semibold tracking-wider text-slate-800">{order.redeemCode}</code></div>{!order.redeemedAt && <OrderCodeActions code={order.redeemCode}/>}</div></div>}</article>)}</div> : <EmptyState><p className="font-medium text-slate-500">还没有关联订单</p><p className="mt-2 text-xs leading-5">在爱发电购买后，请绑定购买时使用的爱发电身份；订单确认后会自动出现在这里。</p></EmptyState>}</Panel></>
}
function OrderState({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-2"><span className="text-slate-400">{icon}</span><span className="text-slate-400">{label}</span><strong className="ml-auto font-medium text-slate-700">{value}</strong></div> }
function statusLabel(value: string | null) { if (!value) return '暂无'; return ({ paid: '已支付', pending: '处理中', completed: '已完成', delivered: '已送达', sent: '已发码', active: '生效中', pending_activation: '待核销', failed: '失败', canceled: '已取消', refunded: '已退款', unknown: '待确认' } as Record<string, string>)[value] || value }
