import { Gauge, Infinity as InfinityIcon, Layers3, Sparkles } from 'lucide-react'
import { requireSession } from '@/lib/account'
import { getAccountEntitlements, getCreditTransactions } from '@/lib/account/read-models'
import { EmptyState, PageIntro, Panel, Status, formatDate, formatLimit } from '@/components/account/ui'

export default async function EntitlementsPage() {
  const session = await requireSession()
  const [data, transactions] = await Promise.all([getAccountEntitlements(session.user.id), getCreditTransactions(session.user.id)])
  return <><PageIntro eyebrow="ENTITLEMENTS" title="我的权益" description="计划权益从生效时间开始计算；计划额度耗尽后，默认计划的基础额度仍然可用。Credits 是额外的增量调用量。"/><div className="space-y-6"><Panel title="订阅计划" description="按计划等级和有效期决定当前生效权益。">{data.plans.length ? <div className="grid gap-4 lg:grid-cols-2">{data.plans.map((item) => <article key={item.id} className={`rounded-2xl border p-5 ${item.active ? 'border-blue-100 bg-blue-50/40' : 'border-slate-100 bg-slate-50/50'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.planName}</p><p className="mt-1 text-xs text-slate-400">{item.description || 'API 访问计划'}</p></div><Status tone={item.active ? 'green' : 'slate'}>{item.active ? '生效中' : '已结束'}</Status></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><Limit icon={<Gauge size={14}/>} label="分钟限速" value={formatLimit(item.rateLimit, '次/分钟')}/><Limit icon={<Layers3 size={14}/>} label="每日额度" value={formatLimit(item.dailyLimit)}/><Limit icon={<Layers3 size={14}/>} label="每周额度" value={formatLimit(item.weeklyLimit)}/><Limit icon={<InfinityIcon size={14}/>} label="每月额度" value={formatLimit(item.monthlyLimit)}/></div><p className="mt-5 border-t border-slate-200/70 pt-4 text-[11px] text-slate-400">{formatDate(item.startsAt)} — {formatDate(item.expiresAt)}</p></article>)}</div> : <EmptyState>尚无额外订阅权益，当前仍可使用默认计划。</EmptyState>}</Panel><Panel title="Credits 增量包" description="订阅额度之外的独立调用量。">{data.credits.length ? <div className="divide-y divide-slate-100">{data.credits.map((item) => <div key={item.id} className="flex items-center gap-4 py-4 first:pt-0 last:pb-0"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Sparkles size={17}/></span><div className="flex-1"><p className="text-sm font-medium">剩余 {item.remainingCredits.toLocaleString('zh-CN')} / {item.credits.toLocaleString('zh-CN')} Credits</p><p className="mt-1 text-[11px] text-slate-400">来源：{item.source} · {formatDate(item.expiresAt)}到期</p></div><Status tone={item.active ? 'green' : 'slate'}>{item.active ? '可用' : '已失效'}</Status></div>)}</div> : <EmptyState>暂无 Credits 增量包。</EmptyState>}</Panel><Panel title="Credits 变动" description="最近 100 条不可变余额记录。">{transactions.length ? <div className="divide-y divide-slate-100">{transactions.map((item) => <div key={item.id} className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"><span className={`w-16 text-sm font-semibold ${item.delta > 0 ? 'text-emerald-600' : 'text-slate-600'}`}>{item.delta > 0 ? '+' : ''}{item.delta}</span><div className="flex-1"><p className="text-xs font-medium text-slate-600">{item.reason === 'api_usage' ? 'API 调用消耗' : item.reason === 'redeem' ? '兑换增量包' : '历史期初余额'}</p><p className="mt-1 text-[11px] text-slate-400">{formatDate(item.createdAt, true)}</p></div><span className="text-xs text-slate-400">余额 {item.balanceAfter.toLocaleString('zh-CN')}</span></div>)}</div> : <EmptyState>暂无 Credits 变动记录。</EmptyState>}</Panel></div></>
}
function Limit({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl bg-white/80 p-3"><span className="flex items-center gap-1.5 text-slate-400">{icon}{label}</span><p className="mt-2 font-medium text-slate-700">{value}</p></div> }
