'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Fingerprint, KeyRound, Laptop, MailCheck, MonitorX, Send, ShieldCheck, Trash2, X } from 'lucide-react'
import { authClient } from '@/lib/auth-client'
import { requestJson } from '@/lib/http-client'
import { Feedback, Panel, Status, dangerButton, formatDate, primaryButton, secondaryButton } from './ui'

type SessionItem = { id: string; createdAt: Date; updatedAt: Date; expiresAt: Date; ipAddress: string | null; userAgent: string | null; current: boolean }
type PasskeyItem = { id: string; name: string | null; deviceType: string; backedUp: boolean; createdAt: Date }
type FeedbackState = { tone: 'success' | 'error' | 'info'; text: string } | null

export function SecuritySettings({ email, emailVerified, hasCredential, twoFactorEnabled, hasTotp, passkeys, sessions }: { email: string; emailVerified: boolean; hasCredential: boolean; twoFactorEnabled: boolean; hasTotp: boolean; passkeys: PasskeyItem[]; sessions: SessionItem[] }) {
  const router = useRouter()
  const [feedback, setFeedback] = useState<FeedbackState>(null)
  const [pending, setPending] = useState('')
  const [newEmail, setNewEmail] = useState('')
  const [passkeyName, setPasskeyName] = useState('')
  const [securityPassword, setSecurityPassword] = useState('')
  const [totpSetup, setTotpSetup] = useState<{ uri: string; qrDataUrl: string; backupCodes: string[] } | null>(null)
  const [totpCode, setTotpCode] = useState('')
  const [confirmSession, setConfirmSession] = useState<string | 'all' | null>(null)
  const run = async (key: string, task: () => Promise<void>, success: string) => {
    setPending(key); setFeedback(null)
    try { await task(); setFeedback({ tone: 'success', text: success }); setConfirmSession(null); router.refresh() }
    catch (error) { const message = error instanceof Error ? error.message : '操作失败，请稍后重试。'; if (message.includes('近期')) { window.location.assign('/reauthenticate?next=/account/security'); return }; setFeedback({ tone: 'error', text: message }) }
    finally { setPending('') }
  }
  const verify = () => run('verify', async () => { const result = await authClient.sendVerificationEmail({ email, callbackURL: '/account/security' }); if (result.error) throw new Error(result.error.message) }, '验证邮件已发送，请检查收件箱。')
  const reset = () => run('reset', async () => { const result = await authClient.requestPasswordReset({ email, redirectTo: '/reset-password' }); if (result.error) throw new Error(result.error.message) }, '密码设置邮件已发送。打开邮件中的链接即可继续。')
  const changeEmail = () => run('email', async () => { const result = await authClient.changeEmail({ newEmail: newEmail.trim(), callbackURL: '/account/security' }); if (result.error) throw new Error(result.error.message) }, '确认邮件已发送。完成验证前，仍使用原邮箱登录。')
  const revoke = (id: string) => run(`session:${id}`, async () => { await requestJson(`/api/account/sessions/${encodeURIComponent(id)}`, { method: 'DELETE' }) }, '该设备会话已结束。')
  const revokeOthers = () => run('others', async () => { await requestJson('/api/account/sessions/revoke-others', { method: 'POST' }) }, '其他设备会话已全部结束。')
  const addPasskey = () => run('passkey:add', async () => { const result = await authClient.passkey.addPasskey({ name: passkeyName.trim() || '我的 Passkey' }); if (result.error) throw new Error(result.error.message); setPasskeyName('') }, 'Passkey 已添加，可在登录页直接使用。')
  const deletePasskey = (id: string) => run(`passkey:${id}`, async () => { const result = await authClient.passkey.deletePasskey({ id }); if (result.error) throw new Error(result.error.message) }, 'Passkey 已移除。')
  const enableEmailMfa = () => run('mfa:email', async () => { const result = await authClient.twoFactor.enable({ method: 'otp', ...(hasCredential ? { password: securityPassword } : {}) }); if (result.error) throw new Error(result.error.message); setSecurityPassword('') }, '邮箱双重验证已启用。下次使用密码登录时会要求验证码。')
  const beginTotp = async () => {
    setPending('mfa:totp'); setFeedback(null)
    const result = await authClient.twoFactor.enable({ method: 'totp', ...(hasCredential ? { password: securityPassword } : {}) })
    setPending('')
    if (result.error || !result.data || result.data.method !== 'totp') { setFeedback({ tone: 'error', text: result.error?.message || '无法开始验证器设置。' }); return }
    let qrDataUrl = ''
    try {
      const QRCode = (await import('qrcode')).default
      qrDataUrl = await QRCode.toDataURL(result.data.totpURI, { errorCorrectionLevel: 'M', margin: 2, width: 256, color: { dark: '#172033', light: '#ffffff' } })
    } catch {
      setFeedback({ tone: 'info', text: '二维码生成失败，请复制下方配置地址手动添加。' })
    }
    setTotpSetup({ uri: result.data.totpURI, qrDataUrl, backupCodes: result.data.backupCodes }); setSecurityPassword('')
  }
  const finishTotp = () => run('mfa:verify', async () => { const result = await authClient.twoFactor.verifyTotp({ code: totpCode }); if (result.error) throw new Error(result.error.message); setTotpSetup(null); setTotpCode('') }, '验证器双重验证已启用，请妥善保存恢复码。')
  const disableMfa = () => run('mfa:disable', async () => { const result = await authClient.twoFactor.disable(hasCredential ? { password: securityPassword } : {}); if (result.error) throw new Error(result.error.message); setSecurityPassword('') }, '双重验证已关闭。')

  return <div className="space-y-6">
    {feedback && <Feedback tone={feedback.tone}>{feedback.text}</Feedback>}
    {totpSetup && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="totp-setup-title"><section className="my-8 w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#edf2ff] text-[#3157d5]"><ShieldCheck size={20}/></span><div><h2 id="totp-setup-title" className="text-xl font-semibold tracking-[-.025em] text-slate-900">连接身份验证器</h2><p className="mt-1 text-xs leading-5 text-slate-500">使用 Google Authenticator、Microsoft Authenticator、1Password 等应用扫描二维码。</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-[220px_minmax(0,1fr)] sm:items-start">{totpSetup.qrDataUrl ? <div className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><img src={totpSetup.qrDataUrl} alt="AccessHub 身份验证器二维码" width={256} height={256} className="aspect-square w-full"/></div> : <div className="grid aspect-square place-items-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-5 text-center text-xs leading-5 text-slate-500">二维码不可用，请使用右侧配置地址手动添加。</div>}<div><p className="text-xs font-medium text-slate-700">1. 扫描二维码</p><p className="mt-1 text-[11px] leading-5 text-slate-400">二维码只在当前浏览器本地生成，不会上传到第三方服务。</p><details className="mt-3 rounded-xl bg-slate-50 p-3"><summary className="cursor-pointer text-[11px] font-medium text-slate-600">无法扫码？查看配置地址</summary><p className="mt-2 break-all font-mono text-[9px] leading-4 text-slate-500">{totpSetup.uri}</p></details><p className="mt-4 text-xs font-medium text-slate-700">2. 输入应用生成的验证码</p><div className="mt-2 flex gap-2"><input autoFocus inputMode="numeric" maxLength={6} autoComplete="one-time-code" value={totpCode} onChange={(event) => setTotpCode(event.target.value.replace(/\D/g, ''))} placeholder="6 位验证码" className="access-input min-w-0 flex-1 text-center tracking-[.16em]"/><button disabled={pending !== '' || totpCode.length !== 6} onClick={() => void finishTotp()} className={primaryButton}>{pending === 'mfa:verify' ? '验证中…' : '确认'}</button></div></div></div><div className="mt-5 rounded-2xl border border-amber-100 bg-amber-50/70 p-4"><p className="text-xs font-medium text-amber-900">恢复码 · 只显示这一次</p><div className="mt-2 grid grid-cols-2 gap-1.5 font-mono text-[10px] text-amber-800 sm:grid-cols-3">{totpSetup.backupCodes.map((code) => <span key={code}>{code}</span>)}</div><p className="mt-2 text-[10px] leading-4 text-amber-700">请保存到密码管理器。手机丢失时，可使用任意一组恢复码登录。</p></div></section></div>}
    <div className="grid items-start gap-6 lg:grid-cols-2">
      <Panel title="主要邮箱" description="用于登录、安全通知和找回账户。"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#edf2ff] text-[#3157d5]"><MailCheck size={18}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{email}</p><div className="mt-2"><Status tone={emailVerified ? 'green' : 'amber'}>{emailVerified ? '已验证' : '等待验证'}</Status></div></div>{!emailVerified && <button disabled={pending === 'verify'} onClick={verify} className={secondaryButton}><Send size={13}/>{pending === 'verify' ? '发送中…' : '重新发送'}</button>}</div>{emailVerified ? <form onSubmit={(event) => { event.preventDefault(); void changeEmail() }} className="mt-5 border-t border-slate-100 pt-5"><label className="text-xs font-medium text-slate-600" htmlFor="new-email">更换主要邮箱</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input id="new-email" type="email" required autoComplete="email" value={newEmail} onChange={(event) => { setNewEmail(event.target.value); setFeedback(null) }} placeholder="name@example.com" className="access-input min-w-0 flex-1"/><button disabled={pending === 'email' || !newEmail.trim() || newEmail.trim().toLowerCase() === email.toLowerCase()} className={secondaryButton}>{pending === 'email' ? '提交中…' : '发送确认'}</button></div><p className="mt-2 text-[11px] leading-5 text-slate-400">我们会先验证这次变更，权益和订单始终留在当前账户。</p></form> : <p className="mt-5 rounded-xl bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-700">验证当前邮箱后，才能更换邮箱或创建密码。</p>}</Panel>
      <Panel title={hasCredential ? '账户密码' : '创建密码'} description={hasCredential ? '需要修改密码时，我们会向已验证邮箱发送一次性链接。' : '增加一种不依赖 OAuth 的备用登录方式。'}><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><KeyRound size={18}/></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{hasCredential ? '密码登录已启用' : '尚未设置密码'}</p><p className="mt-1 text-xs leading-5 text-slate-400">密码只由认证服务验证，页面无法读取。</p></div><Status tone={hasCredential ? 'green' : 'slate'}>{hasCredential ? '已设置' : '未设置'}</Status></div><button disabled={pending === 'reset' || !emailVerified} onClick={reset} className={`${primaryButton} mt-6 w-full sm:w-auto`}><KeyRound size={14}/>{pending === 'reset' ? '正在发送…' : hasCredential ? '发送重设链接' : '发送设置链接'}</button>{!emailVerified && <p className="mt-3 text-[11px] text-amber-600">请先完成邮箱验证。</p>}</Panel>
    </div>
    <div className="grid items-start gap-6 lg:grid-cols-2">
      <Panel title="Passkey" description="使用设备生物识别或安全密钥登录，不需要输入密码。"><div className="space-y-3">{passkeys.length ? passkeys.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="grid size-9 place-items-center rounded-lg bg-[#edf2ff] text-[#3157d5]"><Fingerprint size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name || '未命名 Passkey'}</p><p className="mt-1 text-[11px] text-slate-400">{item.backedUp ? '已同步' : item.deviceType === 'multiDevice' ? '多设备' : '此设备'} · {formatDate(item.createdAt, true)}</p></div><button aria-label="删除 Passkey" disabled={pending === `passkey:${item.id}`} onClick={() => void deletePasskey(item.id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600 disabled:opacity-50"><Trash2 size={15}/></button></div>) : <div className="rounded-xl bg-slate-50 px-4 py-5 text-center text-xs leading-5 text-slate-400">尚未添加 Passkey。添加后即可在登录页使用。</div>}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={passkeyName} onChange={(event) => setPasskeyName(event.target.value)} placeholder="例如：MacBook Touch ID" className="access-input min-w-0 flex-1"/><button disabled={pending !== ''} onClick={() => void addPasskey()} className={primaryButton}><Fingerprint size={14}/>{pending === 'passkey:add' ? '添加中…' : '添加 Passkey'}</button></div></Panel>
      <Panel title="双重验证" description="密码登录后，再使用验证器或邮箱验证码确认身份。"><div className="flex items-center gap-3"><span className={`grid size-10 place-items-center rounded-xl ${twoFactorEnabled ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}><ShieldCheck size={18}/></span><div className="flex-1"><p className="text-sm font-medium">{twoFactorEnabled ? '双重验证已启用' : '尚未启用双重验证'}</p><p className="mt-1 text-xs text-slate-400">{hasTotp ? '当前已配置身份验证器' : twoFactorEnabled ? '当前使用邮箱验证码' : '建议优先使用身份验证器'}</p></div><Status tone={twoFactorEnabled ? 'green' : 'slate'}>{twoFactorEnabled ? '已保护' : '未启用'}</Status></div>{hasCredential && <input type="password" autoComplete="current-password" value={securityPassword} onChange={(event) => setSecurityPassword(event.target.value)} placeholder="输入当前密码以确认变更" className="access-input mt-5 w-full"/>}{totpSetup ? <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50/60 p-4"><p className="text-xs font-medium text-blue-900">在验证器 App 中添加此账户</p><p className="mt-2 break-all rounded-lg bg-white p-3 text-[10px] leading-5 text-slate-500">{totpSetup.uri}</p><p className="mt-3 text-[11px] text-blue-700">恢复码（只显示一次）：</p><div className="mt-2 grid grid-cols-2 gap-1 font-mono text-[10px] text-slate-600">{totpSetup.backupCodes.map((code) => <span key={code}>{code}</span>)}</div><div className="mt-3 flex gap-2"><input inputMode="numeric" value={totpCode} onChange={(event) => setTotpCode(event.target.value.replace(/\D/g, ''))} placeholder="6 位验证码" className="access-input min-w-0 flex-1"/><button disabled={pending !== '' || totpCode.length !== 6} onClick={() => void finishTotp()} className={primaryButton}>{pending === 'mfa:verify' ? '验证中…' : '完成设置'}</button></div></div> : <div className="mt-5 flex flex-wrap gap-2">{!hasTotp && <button disabled={pending !== '' || (hasCredential && !securityPassword)} onClick={() => void beginTotp()} className={primaryButton}><ShieldCheck size={14}/>{pending === 'mfa:totp' ? '准备中…' : '设置验证器'}</button>}{!twoFactorEnabled && <button disabled={pending !== '' || !emailVerified || (hasCredential && !securityPassword)} onClick={() => void enableEmailMfa()} className={secondaryButton}><MailCheck size={14}/>{pending === 'mfa:email' ? '启用中…' : '启用邮箱 MFA'}</button>}{twoFactorEnabled && <button disabled={pending !== '' || (hasCredential && !securityPassword)} onClick={() => void disableMfa()} className={dangerButton}>{pending === 'mfa:disable' ? '关闭中…' : '关闭双重验证'}</button>}</div>}<p className="mt-4 text-[11px] leading-5 text-slate-400">API Key 变更、解绑身份和会话撤销等敏感操作仍要求近期登录；密码登录账户启用 MFA 后，登录时必须完成第二步验证。</p></Panel>
    </div>
    <Panel title="登录设备" description="会话到期后自动失效。发现陌生设备时，先结束会话，再重设密码。"><div className="divide-y divide-slate-100">{sessions.map((item) => <div key={item.id} className="py-4 first:pt-0 last:pb-0"><div className="flex items-center gap-4"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.current ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-50 text-slate-500'}`}><Laptop size={18}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{deviceName(item.userAgent)}</p>{item.current && <Status tone="green">当前设备</Status>}</div><p className="mt-1 truncate text-[11px] text-slate-400">{browserName(item.userAgent)} · {item.ipAddress || 'IP 未记录'}</p><p className="mt-1 text-[11px] tabular-nums text-slate-400">最近活动 {formatDate(item.updatedAt, true)} · {formatDate(item.expiresAt, true)} 到期</p></div>{!item.current && <button disabled={pending === `session:${item.id}`} onClick={() => setConfirmSession(item.id)} className="rounded-lg px-3 py-2 text-xs font-medium text-rose-600 transition hover:bg-rose-50 active:translate-y-px"><MonitorX size={14} className="mr-1.5 inline"/>结束</button>}</div>{confirmSession === item.id && <Confirm text="结束后，这台设备需要重新登录。" pending={pending === `session:${item.id}`} onCancel={() => setConfirmSession(null)} onConfirm={() => void revoke(item.id)}/>}</div>)}</div>{sessions.length > 1 && <div className="mt-5 border-t border-slate-100 pt-5">{confirmSession === 'all' ? <Confirm text={`确认结束另外 ${sessions.length - 1} 个设备的会话？当前设备不受影响。`} pending={pending === 'others'} onCancel={() => setConfirmSession(null)} onConfirm={() => void revokeOthers()}/> : <button onClick={() => setConfirmSession('all')} className={dangerButton}><MonitorX size={14}/>结束其他所有会话</button>}</div>}</Panel>
  </div>
}

function Confirm({ text, pending, onCancel, onConfirm }: { text: string; pending: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="mt-4 flex flex-col gap-3 rounded-xl border border-rose-100 bg-rose-50/70 p-4 sm:flex-row sm:items-center"><p className="flex-1 text-xs leading-5 text-rose-700">{text}</p><div className="flex gap-2"><button disabled={pending} onClick={onCancel} className={secondaryButton}><X size={13}/>取消</button><button disabled={pending} onClick={onConfirm} className={dangerButton}>{pending ? '处理中…' : '确认结束'}</button></div></div> }
function deviceName(userAgent: string | null) { if (!userAgent) return '未知设备'; if (/iPhone|iPad/i.test(userAgent)) return 'iPhone / iPad'; if (/Android/i.test(userAgent)) return 'Android 设备'; if (/Macintosh/i.test(userAgent)) return 'Mac'; if (/Windows/i.test(userAgent)) return 'Windows 设备'; if (/Linux/i.test(userAgent)) return 'Linux 设备'; return '浏览器设备' }
function browserName(userAgent: string | null) { if (!userAgent) return '浏览器未知'; if (/Edg\//.test(userAgent)) return 'Microsoft Edge'; if (/Chrome\//.test(userAgent)) return 'Google Chrome'; if (/Firefox\//.test(userAgent)) return 'Firefox'; if (/Safari\//.test(userAgent)) return 'Safari'; return '浏览器未知' }
