import Link from 'next/link'
import { Activity, ArrowRight, ArrowUpRight, Check, CreditCard, Link2, ReceiptText, ShieldCheck, Sparkles } from 'lucide-react'
import { requireSession } from '@/lib/account'
import { getAccountOverview, getAccountSecurity, getAccountUsage } from '@/lib/account/read-models'
import { PageIntro, Panel, Status, formatDate, formatLimit } from '@/components/account/ui'

export default async function AccountPage() {
  const authSession = await requireSession()
  const [data, security, usage] = await Promise.all([
    getAccountOverview(authSession.user.id),
    getAccountSecurity(authSession.user.id, authSession.session.id),
    getAccountUsage(authSession.user.id, 7),
  ])
  const weekUsage = usage.daily.reduce((sum, item) => sum + item.count, 0)
  const readiness = [Boolean(data.profile?.emailVerified), security.identities.length >= 2, security.hasCredential].filter(Boolean).length
  return <><PageIntro eyebrow="账户概览" title={`你好，${data.profile?.name || authSession.user.name}`} description="先看当前权益和安全状态，再处理需要你关注的事项。"/>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <section className="relative overflow-hidden rounded-[22px] border border-[#cfdafd] bg-[#edf2ff] p-6 md:col-span-2"><div className="absolute -right-12 -top-14 size-40 rounded-full bg-[#3157d5]/10 blur-2xl"/><div className="relative"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-white text-[#3157d5] shadow-sm"><Sparkles size={18}/></span><Status tone="blue">当前权益</Status></div><p className="mt-7 text-xs font-medium text-[#5870b9]">订阅计划</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-3xl font-semibold tracking-[-.04em] text-[#182238]">{data.activePlan?.name || '尚未配置'}</h3><p className="mt-2 text-xs text-slate-500">{data.activePlan?.expiresAt ? `${formatDate(data.activePlan.expiresAt)} 到期` : '持续有效的基础权益'}</p></div><Link href="/account/entitlements" className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#3157d5] hover:text-[#2446bb]">查看完整权益<ArrowUpRight size={14}/></Link></div><div className="mt-6 grid grid-cols-2 gap-3 border-t border-[#cfdaef] pt-4 text-xs"><div><span className="text-slate-400">每日额度</span><strong className="mt-1 block font-medium text-slate-700 tabular-nums">{formatLimit(data.activePlan?.dailyLimit ?? 0)}</strong></div><div><span className="text-slate-400">每月额度</span><strong className="mt-1 block font-medium text-slate-700 tabular-nums">{formatLimit(data.activePlan?.monthlyLimit ?? 0)}</strong></div></div></div></section>
      <Metric label="近 7 日调用" value={weekUsage.toLocaleString('zh-CN')} hint={usage.bySource.length ? `${usage.bySource.length} 个额度来源` : '还没有调用记录'} icon={<Activity size={17}/>} href="/account/usage"/>
      <Metric label="Credits 余额" value={data.creditsRemaining.toLocaleString('zh-CN')} hint="计划额度之后使用" icon={<CreditCard size={17}/>} href="/account/entitlements"/>
    </div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Panel title="账户安全度" description="完成恢复和备用登录设置，避免无法访问账户。"><div className="flex items-end justify-between"><div><strong className="text-3xl font-semibold tabular-nums">{readiness}/3</strong><span className="ml-2 text-xs text-slate-400">项已完成</span></div><span className="text-xs font-medium text-[#3157d5]">{readiness === 3 ? '状态良好' : '建议继续完善'}</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#3157d5] transition-all" style={{ width: `${readiness / 3 * 100}%` }}/></div><div className="mt-5 divide-y divide-slate-100"><Checklist done={Boolean(data.profile?.emailVerified)} label="验证主要邮箱" href="/account/security"/><Checklist done={security.identities.length >= 2} label="绑定备用登录方式" href="/account/connections"/><Checklist done={security.hasCredential} label="设置账户密码" href="/account/security"/></div></Panel><Panel title="账户动态" description="当前账户的重要状态汇总。"><div className="divide-y divide-slate-100"><Row label="主要邮箱" value={data.profile?.email || authSession.user.email} status={<Status tone={data.profile?.emailVerified ? 'green' : 'amber'}>{data.profile?.emailVerified ? '已验证' : '待验证'}</Status>}/><Row label="登录身份" value={`${security.identities.length} 种`} status={<Link href="/account/connections" className="text-xs font-medium text-[#3157d5]">管理</Link>}/><Row label="活跃设备" value={`${security.sessions.length} 个`} status={<Link href="/account/security" className="text-xs font-medium text-[#3157d5]">检查</Link>}/><Row label="历史订单" value={`${data.orderCount} 笔`} status={<Link href="/account/orders" className="text-xs font-medium text-[#3157d5]">查看</Link>}/></div></Panel></div>
    <Panel title="常用操作" description="继续管理调用、登录方式和购买记录。" className="mt-6"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><QuickLink href="/account/security" icon={<ShieldCheck size={17}/>} title="登录与安全"/><QuickLink href="/account/connections" icon={<Link2 size={17}/>} title="账号绑定"/><QuickLink href="/account/usage" icon={<Activity size={17}/>} title="查看用量"/><QuickLink href="/account/orders" icon={<ReceiptText size={17}/>} title="订单与兑换码"/></div></Panel>
  </>
}

function Metric({ label, value, hint, icon, href }: { label: string; value: string; hint: string; icon: React.ReactNode; href: string }) { return <Link href={href} className="group rounded-[20px] border border-[#e3e9f2] bg-white p-5 shadow-[0_14px_42px_rgba(37,53,84,.045)] transition duration-200 hover:-translate-y-0.5 hover:border-[#cad6f7] hover:shadow-[0_18px_48px_rgba(37,53,84,.08)]"><div className="flex items-center justify-between text-slate-400"><p className="text-xs font-medium">{label}</p><span className="transition group-hover:text-[#3157d5]">{icon}</span></div><p className="mt-6 text-3xl font-semibold tracking-[-.035em] tabular-nums">{value}</p><p className="mt-2 text-xs text-slate-400">{hint}</p></Link> }
function Row({ label, value, status }: { label: string; value: string; status: React.ReactNode }) { return <div className="flex items-center gap-4 py-4 first:pt-0 last:pb-0"><div className="min-w-0 flex-1"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-medium">{value}</p></div>{status}</div> }
function Checklist({ done, label, href }: { done: boolean; label: string; href: string }) { return <Link href={href} className="group flex items-center gap-3 py-3.5 first:pt-0 last:pb-0"><span className={`grid size-6 place-items-center rounded-lg ${done ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}`}>{done ? <Check size={14}/> : <ArrowRight size={13}/>}</span><span className={`text-sm ${done ? 'text-slate-500' : 'font-medium text-slate-700'}`}>{label}</span><span className="ml-auto text-[11px] text-slate-400 group-hover:text-[#3157d5]">{done ? '已完成' : '去完成'}</span></Link> }
function QuickLink({ href, icon, title }: { href: string; icon: React.ReactNode; title: string }) { return <Link href={href} className="group flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3.5 text-sm font-medium text-slate-600 transition duration-200 hover:bg-[#edf2ff] hover:text-[#3157d5] active:translate-y-px"><span>{icon}</span>{title}<ArrowRight size={15} className="ml-auto text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-[#7893ee]"/></Link> }
